# Generated by Django 4.0.10 on 2023-07-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='week',
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(choices=[('HOME', 'HOME'), ('AWAY', 'AWAY')], max_length=4),
        ),
    ]
