# Generated by Django 4.0.10 on 2023-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_match_week_alter_match_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
