# Generated by Django 4.0.10 on 2023-07-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_match_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='opponent',
            new_name='away_player',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='player',
            new_name='home_player',
        ),
    ]
