# Generated by Django 4.0.10 on 2023-07-15 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0006_rename_opponent_match_away_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_player',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_player',
        ),
        migrations.AddField(
            model_name='match',
            name='game1_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='game2_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='game3_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_opponent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
