# Generated by Django 4.0.10 on 2023-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_match_opponent_remove_match_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game1_score',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='game2_score',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='game3_score',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
