# Generated by Django 4.0.10 on 2023-07-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_match_game1_score_alter_match_game2_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_player',
            new_name='opponent',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_player',
            new_name='player',
        ),
    ]
