# Generated by Django 4.0.10 on 2023-07-16 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0012_match_opponent_points_lost_match_opponent_points_won_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='opponent_points_lost',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_result',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_points_lost',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_result',
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
