# Generated by Django 4.0.10 on 2023-07-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_remove_match_opponent_points_lost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='opponent_points_won',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_points_won',
        ),
    ]
