# Generated by Django 4.0.10 on 2023-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_match_opponent_result_match_player_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_match_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player_match_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
