# Generated by Django 4.0.10 on 2023-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_match_opponent_match_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opponent_match_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_match_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
