# Generated by Django 4.0.10 on 2023-07-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_points_lost_customuser_points_won'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='points_lost',
            new_name='game_points_lost',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='points_won',
            new_name='game_points_won',
        ),
    ]
