# Generated by Django 4.0.10 on 2023-07-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_points_lost_customuser_game_points_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='match_points_won',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
