# Generated by Django 4.0.10 on 2023-07-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_match_points_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
